#+ summary: grlc exercice 1 - GET method that retrieves all DBpedia bands
#+ endpoint: "http://dbpedia.org/sparql"

SELECT DISTINCT ?id ?v1 ?v2
WHERE {
  ?id a dbo:Band.
  ?id rdfs:label ?v1.
  ?id foaf:depiction ?v2
}
LIMIT 100
